root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/api"
  cmd = "go build -o ./tmp/api cmd/api/main.go"
  delay = 1000
  exclude_dir = ["tmp", "bin", "docs", "migrations", ".git", ".kiro", ".vscode"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
